# This is a basic workflow to help you get started with Actions

name: symbols_updater
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          owner: llvm
          base: master
          head: master
