
name: symbols-update
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  symbols-update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_master
        run: git checkout master
      - name: pull_origin
        run: git pull https://github.com/KiCad/kicad-symbols master
      - name: push_to_master
        run: git push origin
